### ISSUE TITLE
Release on conda-forge

### ISSUE THREAD

**Issue by chrisjsewell** [tsutsu3/linkify-it-py#14]
If you release on conda-forge, then I'll include in markdown-it-py conda requirements 😄 
(If you don't know, you need to make a PR to https://github.com/conda-forge/staged-recipes)

**Comment by chrisjsewell** [comment]
or I can do it?

**Comment by tsutsu3** [comment]
It's okay. That'll be a big help, thanks. 😸

**Comment by tsutsu3** [comment]
Need a new release of inkify-it-py?

https://github.com/conda-forge/staged-recipes/pull/13480

**Comment by chrisjsewell** [comment]
Yes thanks

**Comment by chrisjsewell** [comment]
`[![Anaconda-Server Badge](https://anaconda.org/conda-forge/linkify-it-py/badges/version.svg)](https://anaconda.org/conda-forge/linkify-it-py)`

[![Anaconda-Server Badge](https://anaconda.org/conda-forge/linkify-it-py/badges/version.svg)](https://anaconda.org/conda-forge/linkify-it-py)

**Comment by tsutsu3** [comment]
Thanks @chrisjsewell 🎉 

https://anaconda.org/conda-forge/linkify-it-py
https://anaconda.org/conda-forge/uc-micro-py

I'll add anaconda's badge.
