### ISSUE TITLE
Where is `self.func`?

### ISSUE THREAD

**Issue by Yoric** [tsutsu3/linkify-it-py#16]
I assume that if the code is using `setattr(LinkifyIt, "func", val.get("normalize"))` to define `func`, it should use `getattr` to fetch `func`, instead of `self.func`. As it is right now, this pisses of my Python linter :)

**Comment by tsutsu3** [comment]
Hi @Yoric, Thanks for your issue.

I think you are right, because the pair of `setattr` is `getattr`.
But, I can't reproduce it.

Can you tell me what linter you are using and where you are getting the warning?

**Comment by tsutsu3** [comment]
This issue was closed because old.
